# Tutorial: https://medium.com/@eferhatg/create-react-app-continuous-integration-config-with-circleci-and-aws-2b0238cde169

version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: cimg/node:16.16.0-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      # run linting
      - run: npm run lint

      # run test
      - run: npm test -u

      # run build
      - run: npm run build

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main
